version: '3'

services:
  mongodb:
    image: mongo
    deploy:
      mode: global
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db

  pppauth:
    image: charichu/pppauth:latest
    deploy:
      mode: replicated
      replicas: 1
    container_name: authservice

volumes:
  mongodb: