version: '3'

services:
  mongodb:
    image: mongo
    deploy:
      mode: global
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  pppauth:
    image: charichu/pppauth:0.1.2
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '8000:8000'
    container_name: authservice

volumes:
  mongodb: